---
abstract: 'skip the install rule of MakeMaker'
author:
  - 'Pedro Melo <melo@cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MakeMaker-SkipInstall
requires:
  Dist::Zilla: 0
  Test::Exception: 0
  Test::More: 0.92
resources:
  repository: http://github.com/melo/dist-zilla-tools
version: 1.0
